SECTIONS = [
("01","Personal & Academic Profile",[("preferred_name","Preferred name","text"),("country","Current country","text"),("education","Current/highest education","select|High school|College / A-levels|Bachelor's|Master's|Other"),("academic_performance","Academic performance","select|Exceptional|Strong|Average|Below average|Need to explain"),("subjects_grades","Strongest subjects and grades","textarea")]),
("02","Skills & Capabilities",[("skills","Technical, professional and soft skills","textarea"),("experience","Projects, internships, work and certifications","textarea"),("skill_depth","Depth in strongest skills (1–10)","slider|1|10"),("evidence","Evidence of ability","select|Strong portfolio|Several projects|Mostly certificates|Very little evidence")]),
("03","Learning Style & Decision Making",[("learning_style","Best learning environment","select|Self-directed|Structured classes|Hands-on/projects|Mixed"),("discipline","Consistency without supervision (1–10)","slider|1|10"),("study_method","How do you actually study when nobody supervises you?","textarea"),("independence","Independence (1–10)","slider|1|10"),("risk_tolerance","Tolerance for uncertainty (1–10)","slider|1|10"),("adaptability","Adaptability to unfamiliar cultures/systems (1–10)","slider|1|10"),("decision_style","Major-decision style","select|Evidence/numbers|Intuition|Advice from others|Mixed"),("weaknesses","Biggest weaknesses or recurring failure patterns","textarea")]),
("04","Career & Degree Direction",[("fields","Fields/degrees under consideration","multiselect|Computer Science|Cybersecurity|AI / ML|Software Engineering|Data Science|Engineering|Business|Medicine|Law|Social Sciences|Other"),("why_degree","Why do you want this degree?","textarea"),("why_field","Why this field over alternatives?","textarea"),("career_goal","What does a successful career look like?","textarea"),("work_style","Preferred work style","multiselect|Deep technical|People-facing|Research|Entrepreneurial|Operations|Creative"),("competition","Response to competition","select|Energized|Neutral|Avoid it|Depends")]),
("05","Financial Reality & Scholarships",[("budget","Annual study budget","select|Fully funded required|Under USD 5k|USD 5k–15k|USD 15k–30k|USD 30k+|Unknown"),("funding","Potential funding","multiselect|Scholarship|Family|Savings|Part-time work|Loan|Unknown"),("priority","Main priority","select|Lowest total cost|Best university|Best career outcome|Balanced"),("scholarship","Actively seeking scholarships?","select|Yes|Maybe|No"),("scholarship_type","Funding target","multiselect|Full tuition|Full cost of attendance|Partial tuition|Stipend/living costs|Travel/relocation|Any"),("deadline","Deadline flexibility","select|Very flexible|Somewhat flexible|Only next intake|Only a specific date")]),
("06","Study Abroad Intent & Country Fit",[("abroad","Seriously considering study abroad?","select|Yes|Maybe|No"),("regions","Preferred regions","multiselect|Europe|Asia|North America|Oceania|Middle East|No preference"),("countries","Preferred countries","text"),("language","Would you learn another language for better options?","select|Yes|Maybe|No"),("culture","Importance of cultural/lifestyle fit (1–10)","slider|1|10"),("distance","Comfort being far from home (1–10)","slider|1|10"),("housing","How would you handle a difficult housing market?","textarea")]),
("07","Immigration & Long-Term Goals",[("poststudy","Goal after graduation","select|Return home|Temporary work abroad|Long-term residence|Unsure"),("pr","Importance of PR/citizenship","select|High|Medium|Low"),("work_rights","Importance of post-study work rights (1–10)","slider|1|10"),("bureaucracy","Tolerance for complex bureaucracy (1–10)","slider|1|10")]),
("08","University Strategy",[("selectivity","University target","select|Top/research intensive|Strong public universities|Affordable/accessible|No preference"),("admission_risk","Admission risk preference","select|Reach is acceptable|Balanced|Prefer safer options"),("location","Campus preference","select|Major city|University town|Either")]),
("09","Hidden Opportunities",[("advantages","Unusual advantage, language, certification, experience or connection","textarea"),("regional","Would you consider less-famous regions if outcomes are better?","select|Yes|Maybe|No"),("adjacent","Would you consider an adjacent degree/career if evidence supports it?","select|Yes|Maybe|No")]),
("10","Reality Check & Resilience",[("unwilling","What are you unwilling to sacrifice?","textarea"),("tradeoffs","What difficult trade-offs are acceptable?","textarea"),("plan_b","If your preferred plan fails, what is Plan B?","textarea"),("social","Social/support needs","select|Low|Moderate|High"),("failure_response","What do you do after a serious setback?","textarea"),("accessibility","Any accessibility/safety constraint that materially affects destination choice?","textarea")]),
("11","Final Constraints & Questions",[("constraints","Any constraint that could materially change the recommendation?","textarea"),("question","What is the single most important question Avenor must answer?","textarea"),("success_definition","What would make this assessment genuinely useful?","textarea")])
]
