from io import BytesIO
from datetime import datetime

from reportlab.lib.pagesizes import LETTER
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, ListFlowable, ListItem, HRFlowable
)

NAVY = colors.HexColor("#0a1220")
BRASS = colors.HexColor("#c9a227")
TEAL = colors.HexColor("#1f8a8c")
INK = colors.HexColor("#1c2431")
MUTED = colors.HexColor("#5b6579")


def to_markdown(name: str, report: dict, universities: list | None = None) -> str:
    lines = []
    lines.append(f"# Avenor Assessment Dossier")
    lines.append(f"**Prepared for:** {name or 'Candidate'}  ")
    lines.append(f"**Date:** {datetime.now().strftime('%d %B %Y')}\n")
    lines.append(f"## Verdict: {report.get('verdict','')} — {report.get('overall_score','')}/100\n")
    lines.append(report.get("summary", ""))
    lines.append("\n### Strengths")
    for s in report.get("strengths", []):
        lines.append(f"- {s}")
    lines.append("\n### Risks")
    for r in report.get("risks", []):
        lines.append(f"- {r}")
    lines.append("\n### Financial Reality Check")
    lines.append(report.get("financial_reality_check", ""))
    lines.append("\n### Recommended Pathways")
    for p in report.get("recommended_pathways", []):
        lines.append(f"- **{p.get('path','')}** — {p.get('why','')} _(timeline: {p.get('timeline','')})_")
    lines.append("\n### Country / Region Fit")
    for c in report.get("country_fit", []):
        lines.append(f"- **{c.get('region_or_country','')}**: {c.get('fit_score','')}/100 — {c.get('reason','')}")
    lines.append("\n### Immediate Next Steps")
    for i, step in enumerate(report.get("immediate_next_steps", []), 1):
        lines.append(f"{i}. {step}")
    lines.append("\n### Single Most Important Risk")
    lines.append(report.get("single_most_important_risk", ""))
    if universities:
        lines.append("\n### University Ranking Comparator")
        header = "| University | Country | QS | THE | ARWU | US News | CWUR |"
        sep = "|---|---|---|---|---|---|---|"
        lines.append(header)
        lines.append(sep)
        for u in universities:
            lines.append(
                f"| {u.get('University','')} | {u.get('Country','')} | {u.get('QS','–')} | "
                f"{u.get('THE','–')} | {u.get('ARWU','–')} | {u.get('US News','–')} | {u.get('CWUR','–')} |"
            )
    lines.append("\n---\n*Generated by Avenor. Ranking figures are illustrative sample data — verify against official QS, THE, ARWU, US News and CWUR sources before final decisions.*")
    return "\n".join(lines)


def _styles():
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name="AvenorTitle", fontSize=22, leading=26, textColor=NAVY, spaceAfter=4, fontName="Helvetica-Bold"))
    styles.add(ParagraphStyle(name="AvenorMeta", fontSize=9, textColor=MUTED, spaceAfter=14))
    styles.add(ParagraphStyle(name="AvenorH2", fontSize=13, leading=16, textColor=NAVY, spaceBefore=14, spaceAfter=6, fontName="Helvetica-Bold"))
    styles.add(ParagraphStyle(name="AvenorBody", fontSize=10, leading=15, textColor=INK))
    styles.add(ParagraphStyle(name="AvenorVerdict", fontSize=14, leading=18, textColor=TEAL, fontName="Helvetica-Bold", spaceAfter=10))
    return styles


def to_pdf_bytes(name: str, report: dict, universities: list | None = None) -> bytes:
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=LETTER,
        topMargin=0.75 * inch, bottomMargin=0.75 * inch,
        leftMargin=0.8 * inch, rightMargin=0.8 * inch,
    )
    styles = _styles()
    story = []

    story.append(Paragraph("AVENOR", styles["AvenorTitle"]))
    story.append(Paragraph(
        f"Study-Abroad Readiness Dossier &nbsp;•&nbsp; Prepared for {name or 'Candidate'} &nbsp;•&nbsp; {datetime.now().strftime('%d %B %Y')}",
        styles["AvenorMeta"]
    ))
    story.append(HRFlowable(width="100%", color=BRASS, thickness=1))
    story.append(Spacer(1, 10))

    story.append(Paragraph(f"{report.get('verdict','')} — {report.get('overall_score','')}/100", styles["AvenorVerdict"]))
    story.append(Paragraph(report.get("summary", ""), styles["AvenorBody"]))

    story.append(Paragraph("Strengths", styles["AvenorH2"]))
    story.append(ListFlowable(
        [ListItem(Paragraph(s, styles["AvenorBody"])) for s in report.get("strengths", [])],
        bulletType="bullet"
    ))

    story.append(Paragraph("Risks", styles["AvenorH2"]))
    story.append(ListFlowable(
        [ListItem(Paragraph(r, styles["AvenorBody"])) for r in report.get("risks", [])],
        bulletType="bullet"
    ))

    story.append(Paragraph("Financial Reality Check", styles["AvenorH2"]))
    story.append(Paragraph(report.get("financial_reality_check", ""), styles["AvenorBody"]))

    story.append(Paragraph("Recommended Pathways", styles["AvenorH2"]))
    for p in report.get("recommended_pathways", []):
        story.append(Paragraph(
            f"<b>{p.get('path','')}</b> — {p.get('why','')} <i>(timeline: {p.get('timeline','')})</i>",
            styles["AvenorBody"]
        ))
        story.append(Spacer(1, 4))

    story.append(Paragraph("Country / Region Fit", styles["AvenorH2"]))
    for c in report.get("country_fit", []):
        story.append(Paragraph(
            f"<b>{c.get('region_or_country','')}</b>: {c.get('fit_score','')}/100 — {c.get('reason','')}",
            styles["AvenorBody"]
        ))
        story.append(Spacer(1, 4))

    story.append(Paragraph("Immediate Next Steps", styles["AvenorH2"]))
    story.append(ListFlowable(
        [ListItem(Paragraph(s, styles["AvenorBody"])) for s in report.get("immediate_next_steps", [])],
        bulletType="1"
    ))

    story.append(Paragraph("Single Most Important Risk", styles["AvenorH2"]))
    story.append(Paragraph(report.get("single_most_important_risk", ""), styles["AvenorBody"]))

    if universities:
        story.append(Paragraph("University Ranking Comparator", styles["AvenorH2"]))
        data = [["University", "Country", "QS", "THE", "ARWU", "US News", "CWUR"]]
        for u in universities:
            data.append([
                u.get("University", ""), u.get("Country", ""),
                str(u.get("QS", "–")), str(u.get("THE", "–")), str(u.get("ARWU", "–")),
                str(u.get("US News", "–")), str(u.get("CWUR", "–")),
            ])
        table = Table(data, hAlign="LEFT", colWidths=[1.7 * inch, 1.0 * inch, 0.5 * inch, 0.5 * inch, 0.5 * inch, 0.6 * inch, 0.5 * inch])
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), NAVY),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#dcdcdc")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f4f1e8")]),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ]))
        story.append(table)

    story.append(Spacer(1, 14))
    story.append(HRFlowable(width="100%", color=BRASS, thickness=0.6))
    story.append(Paragraph(
        "Generated by Avenor. Ranking figures are illustrative sample data — verify against official "
        "QS, THE, ARWU, US News and CWUR sources before final decisions.",
        styles["AvenorMeta"]
    ))

    doc.build(story)
    return buffer.getvalue()
